### ISSUE TITLE
圖片預覽會被切掉

### ISSUE THREAD

**Issue by laichiaheng** [a9650615/hentai#3]
![111](https://cloud.githubusercontent.com/assets/9532105/15267302/85c4c094-19f0-11e6-8900-45c32660a673.png)
![222](https://cloud.githubusercontent.com/assets/9532105/15267303/88832974-19f0-11e6-9500-b1de9251df2e.png)

**Comment by a9650615** [comment]
因為我還想不到好的顯示方式

**Comment by laichiaheng** [comment]
要不要像官方那樣，給個固定比例或大小的直條長方形框框，如果圖片比例與框框不合就縮小，不讓圖片超過範圍？
![official](https://cloud.githubusercontent.com/assets/9532105/15268679/7b25adbe-1a19-11e6-83a7-1294e550f1a8.png)

**Comment by a9650615** [comment]
可是如果是寬圖就會上下留白邊

**Comment by laichiaheng** [comment]
但至少預覽圖較完整

**Comment by a9650615** [comment]
也是 好 我下次改一下

**Comment by laichiaheng** [comment]
請問您有在哪邊推廣這個軟體嗎？

**Comment by a9650615** [comment]
只有 http://acgn-moemoe.tw/ 而已
